export const ITEMS_FETCH_REQUEST = 'ITEMS_FETCH_REQUEST';
export const ITEMS_FETCH_ERROR = 'ITEMS_FETCH_ERROR';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';

export const ITEMS_EDIT_REQUEST = 'ITEMS_EDIT_REQUEST';
export const ITEMS_EDIT_ERROR = 'ITEMS_EDIT_ERROR';
export const ITEMS_EDIT_SUCCESS = 'ITEMS_EDIT_SUCCESS';

export const IMAGE_EDIT_REQUEST = 'IMAGE_EDIT_REQUEST';
export const IMAGE_EDIT_ERROR = 'IMAGE_EDIT_ERROR';
export const IMAGE_EDIT_SUCCESS = 'IMAGE_EDIT_SUCCESS';
